return {
  { 'neovim/nvim-lspconfig' },
  { 'matze/vim-move' },
  { "ellisonleao/gruvbox.nvim" },
  { 'nvim-lua/plenary.nvim' },
  { 'nvim-tree/nvim-web-devicons' },
  { 'nvim-telescope/telescope.nvim' },
  { "nvim-telescope/telescope-file-browser.nvim" },
  { 'nvim-tree/nvim-tree.lua' },
  { 'hrsh7th/cmp-nvim-lsp' },
  { 'hrsh7th/cmp-buffer'},
  { 'hrsh7th/cmp-path'},
  { 'hrsh7th/cmp-cmdline'},
  { 'hrsh7th/nvim-cmp' },
  { 'L3MON4D3/LuaSnip' },
  { 'saadparwaiz1/cmp_luasnip' },
  { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
  { 'pwntester/octo.nvim'},
  { 'ggandor/leap.nvim' },
  { 'ntpeters/vim-better-whitespace' },
  { 'sheerun/vim-polyglot' },
  { 'mfussenegger/nvim-dap' },
  { 'rcarriga/nvim-dap-ui' },
  { 'folke/neodev.nvim' },
  { 'kdheepak/lazygit.nvim' },
  { 'lewis6991/gitsigns.nvim' },
}
